hmcts/wa-shared-infrastructure

.gitignore
Jenkinsfile_CNP
README.md
key-vault.tf
main.tf
resource-group.tf
state.tf
variables.tf

Initial setup for wa shared infra

Initial setup for wa shared infra

---

aat.tfvars
key-vault.tf
main.tf

Set value for managed identity in AAT

Set value for managed identity in AAT

---

servicebus.tf

Added ASB with terraform
```
[ ] Yes
[x ] No
```

Added ASB terraform

---

servicebus.tf

https://tools.hmcts.net/jira/browse/RWA-339

RWA-339 point to the ccd rg

---

action-groups.tf
alerts.tf
key-vault.tf

https://tools.hmcts.net/jira/browse/RWA-342
RWA-342: Add alerts for dead letter queue messages
```
[ ] Yes
[ x] No
```

RWA-342: Add alerts for dead letter queue messages

---

action-groups.tf

reverting change

---

alerts.tf

https://tools.hmcts.net/jira/browse/RWA-506
RWA-506: Add app insights alert for task unconfigured
```
[ ] Yes
[x ] No
```

RWA-506: Add app insights alert for task unconfigured

---

alerts.tf

Update alert query
```
[ ] Yes
[x ] No
```

Update alert query

---

action-groups.tf

https://tools.hmcts.net/jira/browse/RWA-506
Add action group inside camunda app insights
```
[ ] Yes
[ x] No
```

Add action group inside camunda app insights

---

alerts.tf

Increase alert polling time and time window to 60 mins
```
[ ] Yes
[x ] No
```

Increase alert polling time and time window to 60 mins

---

Jenkinsfile_CNP
state.tf

https://tools.hmcts.net/jira/browse/RWA-775
Updated terraform to fix jenkins build
```
[ ] Yes
[x] No
```

RWA 775 terraform fix

---

servicebus.tf

https://tools.hmcts.net/jira/browse/RWA-901
Add filter to listen only live services
```
[ ] Yes
[ ] No
```

feat:Add filter to listen only live services (RWA-901)

---

prod.tfvars
servicebus.tf
variables.tf

https://tools.hmcts.net/jira/browse/RWA-720
Allow sscs for case event handler
```
[ ] Yes
[ ] No
```

feat:Allow sscs for case event handler(RWA-720)

---

servicebus.tf

Change filter names
```
[ ] Yes
[ x] No
```

Change names

---

servicebus.tf

Add Filters independently:
- aat should have message_Context
- other environments should have the jurisdiction filter
```
[ ] Yes
[x ] No
```

Independent filters

---

alerts.tf

RWA-1329 - add common_tags to alerts

---

alerts.tf

[RWA-933](https://tools.hmcts.net/jira/browse/RWA-933)
See ticket [RWA-933](https://tools.hmcts.net/jira/browse/RWA-933)
```
[ ] Yes
[ X] No
```

RWA-933: Set up alerts for CCD unprocessable messages

---

alerts.tf

Fix alert appinsight env
```
[ ] Yes
[ X] No
```

Fix alert appinsight env

---

alerts.tf

Remove changes for RWA-933 to fix a pipeline issue
```
[ ] Yes
[ X] No
```

Fix alert env

---

alerts.tf

[RWA-933](https://tools.hmcts.net/jira/browse/RWA-933)
see ticket
```
[ ] Yes
[ X] No
```

RWA-933: Set up alerts

---

alerts.tf
application-insights.tf
key-vault.tf
main.tf
resource-group.tf

https://tools.hmcts.net/jira/browse/RWA-1159
Slight tweaks to the tags for azure resources. This is to follow the tagging policy for HMCTS
and allow better auditing of azure resources
```
[ ] Yes
[X ] No
```

RWA-1159 Fix azure tags compliance policy

---

servicebus.tf
state.tf

bumping azurerm version

---

alerts.tf

https://tools.hmcts.net/jira/browse/RWA-1100
initially TASK_INITIATION_FAILURES  alert created
```
[ ] Yes
[X] No
```

RWA-1100 TASK_INITIATION_FAILURES and TASK_TERMINATION_FAILURES alerts

---

application-insights.tf

https://tools.hmcts.net/jira/browse/RWA-1154
added app_insights_connection_string needed for Appinsight v3 upgrade
```
[ ] Yes
[x] No
```

RWA-1154: added app_insights_connection_string

---

alerts.tf

[RWA-1521](https://tools.hmcts.net/jira/browse/RWA-1521)
```
[ ] Yes
[x] No
```

RWA-1521 Camunda - Switch off Task configuration code

---

renovate.json

https://tools.hmcts.net/jira/browse/RWA-1848
enabled renovate with terraform support
```
[ ] Yes
[x] No
```

RWA-1848: enabled renovate with terraform support

---

servicebus.tf

RWA-1995
Clean up old subscription for aat
```
[ ] Yes
[ ] No
```

Clean up old subscription for aat(RWA-1995)

---

servicebus.tf

[RWA-1995](https://tools.hmcts.net/jira/browse/RWA-1995)
Remove old service bus  susbscription from prod
```
[ ] Yes
[ ] No
```

Remove old service bus  susbscription from prod (RWA-1995)

---

alerts.tf

[RWA-1827](https://tools.hmcts.net/jira/browse/RWA-1827)
see [RWA-1827](https://tools.hmcts.net/jira/browse/RWA-1827)
```
[ ] Yes
[ X] No
```

RWA-1827 Add reconfiguration exception alert

---

prod.tfvars

[RWA-1999](https://tools.hmcts.net/jira/browse/RWA-1999)
```
[ ] Yes
[X ] No
```

RWA-1999 Enable Civil

---

prod.tfvars
variables.tf

https://tools.hmcts.net/jira/browse/RWA-2270
```
[ ] Yes
[X] No
```

RWA-2270-privateLaw added to ASB filter

---

aat.tfvars
demo.tfvars
variables.tf

[RWA-2153](https://tools.hmcts.net/jira/browse/RWA-2153)
```
[ ] Yes
[ X] No
```

Updating allowed_jurisdictions for different environments

---

alerts.tf

Fix failing pipeline due to variable type
```
[ ] Yes
[X ] No
```

Change variable type for alerts declared variables

---

alerts.tf

https://tools.hmcts.net/jira/browse/RWA-2367
```
[ ] Yes
[X] No
```

RWA-2367-UNPROCESSABLE query extended

---

perftest.tfvars

https://tools.hmcts.net/jira/browse/RWA-2389
```
[ ] Yes
[X] No
```

RWA-2389-perftest variables file added

---

ithc.tfvars
variables.tf

[RWA-2513](https://tools.hmcts.net/jira/browse/RWA-2513)
See ticket 
```
[ ] Yes
[ X] No
```

Enable Private law in Ithc

---

alerts.tf

https://tools.hmcts.net/jira/browse/RWA-2544
FIND_PROBLEM_MESSAGES alert fix
```
[ ] Yes
[x ] No
```

RWA-2544 fix FIND_PROBLEM_MESSAGES alert

---

demo.tfvars

https://tools.hmcts.net/jira/browse/COT-254
```
[ ] Yes
[ ] No
```

COT-254:Onboarded Special Tribunals To TM

---

aat.tfvars

https://tools.hmcts.net/jira/browse/COT-254 
```
[ ] Yes
[ ] No
```

COT-254: Whitelist SpecialTribs to TM on AAT

---

aat.tfvars

https://tools.hmcts.net/jira/browse/COT-304 
```
[ ] Yes
[ ] No
```

COT-304: Whitelist SSCS to TM

---

perftest.tfvars

https://tools.hmcts.net/jira/browse/COT-361
```
[ ] Yes
[ ] No
```

Whitelist Publiclaw to Perftest

---

alerts.tf

https://tools.hmcts.net/jira/browse/RWA-2560
Remove customDimensions[\"LoggingLevel\"] from alerts as it is not present anymore
```
[ ] Yes
[ x] No
```

RWA-2560: Remove LoggingLevel

---

prod.tfvars

https://tools.hmcts.net/jira/browse/COT-251
```
[ ] Yes
[ ] No
```

COT-251: Whitelist Publiclaw on TM Prod

---

perftest.tfvars

https://tools.hmcts.net/jira/browse/COT-232 
```
[ ] Yes
[ ] No
```

COT-232: Whitelist SSCS Benefit to TM

---

aat.tfvars
demo.tfvars
perftest.tfvars

https://tools.hmcts.net/jira/browse/COT-238 
```
[ ] Yes
[ ] No
```

COT-238:Enable FR TM

---

alerts.tf

RWA-2634: Detecting Replication Problems

---

alerts.tf
prod.tfvars
variables.tf

https://tools.hmcts.net/jira/browse/RWA-2707
Added failed task deletion alert
```
[ ] Yes
[x] No
```

RWA-2707 add failed task deletion alert

---

perftest.tfvars

https://tools.hmcts.net/jira/browse/COT-464
```
[ ] Yes
[ ] No
```

COT-495: Enable ET on Perftest

---

aat.tfvars
key-vault.tf
renovate.json
variables.tf

Jira: https://tools.hmcts.net/jira/browse/RWA-2866

Add managed identities for key vaults

---

prod.tfvars

https://tools.hmcts.net/jira/browse/RWA-3215

RWA-3215: Whitelist SSCS on prod

---

ithc.tfvars
perftest.tfvars

https://tools.hmcts.net/jira/browse/RWA-3851
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change

RWA-3851: Whitelist ST_CIC ithc and perftest

---

prod.tfvars

See [RWA-3214](https://tools.hmcts.net/jira/browse/RWA-3214)

RWA-3214: Whitelist ST on prod

---

ithc.tfvars

See [RWA-4548](https://tools.hmcts.net/jira/browse/RWA-4548)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

RWA-4548: Enable PUBLICLAW
